# Generated by Django 2.1.8 on 2019-05-04 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clubProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('entryDate', models.DateField()),
                ('productURL', models.URLField()),
                ('productdescription', models.TextField()),
            ],
            options={
                'db_table': 'clubproduct',
            },
        ),
        migrations.CreateModel(
            name='clubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
                ('typedescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='clubproduct',
            name='clubtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clubapp.clubType'),
        ),
        migrations.AddField(
            model_name='clubproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
