# Generated by Django 2.1.8 on 2019-05-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0002_auto_20190504_1954'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resource',
            table='resources',
        ),
    ]
