# Generated by Django 2.1.8 on 2019-05-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0003_auto_20190506_0826'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resource',
            table='resource',
        ),
    ]
