# Generated by Django 2.1.8 on 2019-05-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0004_auto_20190506_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': 'resources'},
        ),
        migrations.AlterModelTable(
            name='meetingminutes',
            table='attendance',
        ),
    ]
