# Generated by Django 2.1.8 on 2019-05-20 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubapp', '0006_event_eventurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name_plural': 'meetings'},
        ),
        migrations.RemoveField(
            model_name='meetingminutes',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='meetingminutes',
            name='minutes',
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='meetingdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='meetingminutes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='meeting',
        ),
        migrations.AlterModelTable(
            name='meetingminutes',
            table='meetingminutes',
        ),
    ]
