# Generated by Django 2.1.8 on 2019-05-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0007_auto_20190519_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutes',
            name='meetingdate',
            field=models.DateField(auto_now=True),
        ),
    ]
