# Generated by Django 2.1.8 on 2019-05-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0009_remove_meetingminutes_meetingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='meetingminutesdate',
            field=models.DateField(auto_now=True),
        ),
    ]
