# Generated by Django 2.1.8 on 2019-05-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0010_meetingminutes_meetingminutesdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
