# Generated by Django 2.1.8 on 2019-05-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0011_auto_20190521_1202'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meetingminutes',
            table='minutes',
        ),
    ]
