# Generated by Django 2.1.8 on 2019-05-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0014_auto_20190523_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingminutes',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name_plural': 'clubapp_meetings'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='clubapp_event',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='clubapp_meeting',
        ),
        migrations.DeleteModel(
            name='MeetingMinutes',
        ),
    ]
